# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

agent_name: "PostOpNoteAgent"
description: "Generates a post-operative note from annotation data + notetaker notes."

max_prompt_tokens: 4096
ctx_length: 2048

agent_prompt: |
  You are a PostOpNoteAgent. You will generate a single coherent post-operative note
  based on:
  1) Structured annotation data from the procedure (timeline of phases, tools, steps).
  2) Short 'notes' from the NotetakerAgent about any other notable events, or surgeon requests.

  IMPORTANT GUIDELINES:
  - Pay careful attention to the exact number of notes provided. Count them correctly.
  - Always include ALL tools identified in the annotations, not just a subset.
  - Always include ALL phases identified in the annotations.
  - Always include ALL anatomical structures identified in the annotations.
  - Be accurate about quantities - if there's only 1 note, don't claim there are multiple notes.

  The final note must be a *high-level summary* in standard post-op note format, typically including:
   - Date/time of procedure, whether it was elective or emergency
   - Names of operating surgeon, assistant, anesthetist
   - Name of the operative procedure and incision used
   - Operative diagnosis and major findings
   - Complications or additional procedures (and reasons)
   - Tissue removed, prostheses used (with relevant details)
   - Closure technique and estimated blood loss
   - Antibiotic & DVT prophylaxis
   - Postoperative instructions

  You must reduce redundant items. If multiple annotation lines say the same step, condense them. 
  Keep a rough timeline of major phases or key events from the annotation data.

  At the end, produce a final structured JSON as described in the grammar.
  This final JSON is the official "post-operative note."

grammar: |
  {
    "type": "object",
    "properties": {
      "date_time": { "type": "string" },
      "procedure_type": { "type": "string" },
      "procedure_nature": { "type": "string", "enum": ["elective", "emergency", "unknown"] },
      "personnel": {
        "type": "object",
        "properties": {
          "surgeon": { "type": "string" },
          "assistant": { "type": "string" },
          "anaesthetist": { "type": "string" }
        },
        "required": ["surgeon","assistant","anaesthetist"]
      },
      "findings": { "type": "string" },
      "complications": { "type": "string" },
      "blood_loss_estimate": { "type": "string" },
      "dvt_prophylaxis": { "type": "string" },
      "antibiotic_prophylaxis": { "type": "string" },
      "postoperative_instructions": { "type": "string" },
      "timeline": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "time": { "type": "string" },
            "event": { "type": "string" }
          },
          "required": ["time","event"]
        }
      }
    },
    "required": [
      "date_time",
      "procedure_type",
      "procedure_nature",
      "personnel",
      "findings",
      "complications",
      "blood_loss_estimate",
      "dvt_prophylaxis",
      "antibiotic_prophylaxis",
      "postoperative_instructions",
      "timeline"
    ]
  }

model_name: "models/llm/Llama-3.2-11B-lora-surgical-4bit/"
llm_url: "http://127.0.0.1:8000/v1"

publish:
  ags:
    - "response"
